services:
  mysql:
    build: ./mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - app_network

  # php-apache:
  #   build: ./php_apache
  #   container_name: php-apache
  #   ports:
  #     - "8080:80"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mysql
  #   networks:
  #     - app_network

  scrapy:
    build: ./scrapy
    container_name: scrapy
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
